export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT'; 
export const REGISTER_AUTH_SUCCESS = 'REGISTER_AUTH_SUCCESS';


export const OPEN_ADD_CHAT_POPUP="OPEN_ADD_CHAT_POPUP";
export const CLOSE_ADD_CHAT_POPUP="CLOSE_ADD_CHAT_POPUP";

export const ADD_MESSAGE="ADD_MESSAGE";
export const SET_MESSAGES="SET_MESSAGES";

export const GET_CHATS_SUCCESS="GET_CHATS_SUCCESS";
export const CLEAR_ALL_CHATS="CLEAR_ALL_CHATS";
export const GET_NEW_CHATID="GET_NEW_CHATID";

export const SET_NEW_ACTIVE_USER="SET_NEW_ACTIVE_USER";
export const SET_LOGGEDIN_USER="SET_LOGGEDIN_USER";